version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - "32700:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  user
      POSTGRES_PASSWORD:  admin_pwd1222
      POSTGRES_DB: orders_data
