version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  user_app
      POSTGRES_PASSWORD:  user_pwd_01
      POSTGRES_DB: spreadsheet

  db_redactor:
    build:
      context: .
      dockerfile: db_redactor.Dockerfile
    ports:
      - 8000:8000
    depends_on:
      - db
