version: '3'
services:
  db:
    image:  postgres:11
    ports:
      - "32700:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER:  user_app
      POSTGRES_PASSWORD:  user_pwd_01
      POSTGRES_DB: spreadsheet
